mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 346, in execute_state
    ).evaluate(global_state)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 260, in evaluate
    result = instruction_mutator(global_state)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 192, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 127, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/instructions.py", line 1855, in return_
    global_state.current_transaction.end(global_state, return_data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/transaction_models.py", line 180, in end
    raise TransactionEndSignal(global_state, revert)
mythril.laser.ethereum.transaction.transaction_models.TransactionEndSignal: (<mythril.laser.ethereum.state.global_state.GlobalState object at 0x7fa6cb2c0470>, False)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 162, in fire_lasers
    custom_modules_directory=self.custom_modules_directory,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/analysis/symbolic.py", line 166, in __init__
    world_state=world_state,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 175, in sym_exec
    self._execute_transactions(created_account.address)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 216, in _execute_transactions
    execute_message_call(self, address)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/transaction/symbolic.py", line 108, in execute_message_call
    laser_evm.exec()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 253, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/ethereum/svm.py", line 386, in execute_state
    check_potential_issues(global_state)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/analysis/potential_issues.py", line 87, in check_potential_issues
    state, state.world_state.constraints + potential_issue.constraints
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/analysis/solver.py", line 65, in get_transaction_sequence
    model = get_model(tx_constraints, minimize=minimize)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/support/model.py", line 57, in get_model
    result = s.check()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/smt/solver/solver_statistics.py", line 19, in function_wrapper
    result = func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/laser/smt/solver/solver.py", line 55, in check
    evaluate = self.raw.check(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/z3/z3.py", line 7534, in check
    return CheckSatResult(Z3_optimize_check(self.ctx.ref(), self.optimize, num, _assumptions))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/z3/z3core.py", line 4468, in Z3_optimize_check
    _elems.Check(a0)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/z3/z3core.py", line 1420, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'push canceled'


---------------------------------------------
For contract 0xe3013029af5f33ec3fc0f3b71508acb775ddc196.sol
Tool Runtime = 2877.339339230006 seconds
#############################################